// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProcedureMakerServer;

#nullable disable

namespace ProcedureMakerServer.Migrations
{
    [DbContext(typeof(ProcedureContext))]
    [Migration("20231008053836_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EFCoreBase.Entities.LawyerFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CourtNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourtType")
                        .HasColumnType("integer");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("LawyerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LawyerId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("JWTAuth.Entities.RoleBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UserBaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserBaseId");

                    b.ToTable("RoleBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("RoleBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JWTAuth.Entities.UserBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserBase");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("JWTAuth.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("ProcedureMakerServer.Entities.Lawyer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourtRole")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasJuridicalAid")
                        .HasColumnType("boolean");

                    b.Property<string>("HomePhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MobilePhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkPhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Lawyers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c931cc96-4e87-49f6-8037-111041bcc774"),
                            Address = "",
                            City = "",
                            Country = "",
                            CourtRole = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "richerf@master.com",
                            FirstName = "fred",
                            HasJuridicalAid = false,
                            HomePhoneNumber = "",
                            LastName = "richer",
                            MobilePhoneNumber = "",
                            PostalCode = "",
                            SocialSecurityNumber = "",
                            WorkPhoneNumber = ""
                        },
                        new
                        {
                            Id = new Guid("3284ac9d-81b2-4fc0-82fb-47855df39814"),
                            Address = "",
                            City = "",
                            Country = "",
                            CourtRole = 1,
                            DateOfBirth = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grangerf@master.com",
                            FirstName = "john",
                            HasJuridicalAid = false,
                            HomePhoneNumber = "",
                            LastName = "granger",
                            MobilePhoneNumber = "",
                            PostalCode = "",
                            SocialSecurityNumber = "",
                            WorkPhoneNumber = ""
                        });
                });

            modelBuilder.Entity("ProcedureMakerServer.Authentication.Role", b =>
                {
                    b.HasBaseType("JWTAuth.Entities.RoleBase");

                    b.HasDiscriminator().HasValue("Role");
                });

            modelBuilder.Entity("ProcedureMakerServer.Authentication.User", b =>
                {
                    b.HasBaseType("JWTAuth.Entities.UserBase");

                    b.HasDiscriminator().HasValue("User");
                });

            modelBuilder.Entity("EFCoreBase.Entities.LawyerFile", b =>
                {
                    b.HasOne("ProcedureMakerServer.Entities.Lawyer", "Lawyer")
                        .WithMany()
                        .HasForeignKey("LawyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lawyer");
                });

            modelBuilder.Entity("JWTAuth.Entities.RoleBase", b =>
                {
                    b.HasOne("JWTAuth.Entities.UserBase", null)
                        .WithMany("Roles")
                        .HasForeignKey("UserBaseId");
                });

            modelBuilder.Entity("JWTAuth.Entities.UserRole", b =>
                {
                    b.HasOne("JWTAuth.Entities.RoleBase", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JWTAuth.Entities.UserBase", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JWTAuth.Entities.RoleBase", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("JWTAuth.Entities.UserBase", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
